const state={runs:[],metrics:null,enabled:new Set(['deaths','floors','deck','cards','economy']),layout:JSON.parse(localStorage.getItem('slaytracker.layout')||'{}')};
const widgets=[['floorProgress','Linha','Progressao por floor','floors',renderFloorProgress],['deckWinRate','Barras','Tamanho do deck x win rate','deck',renderDeckWinRate],['cardStats','Tabela','Pick rate por carta','cards',renderCardStats],['deathStats','Tabela','Mortes por encontro','deaths',renderDeathStats],['runTable','Tabela','Historico de runs','floors',renderRunTable],['economy','Barras','Ouro, dano e cura','economy',renderEconomy]].map(([id,type,title,analysis,render])=>({id,type,title,analysis,render}));
const metricOptions=[['runIndex','Run'],['ascension','Ascension'],['floor','Floor alcancado'],['deckSize','Tamanho do deck'],['win','Vitoria'],['runTimeMinutes','Tempo em minutos'],['goldGained','Ouro ganho'],['goldSpent','Ouro gasto'],['damageTaken','Dano recebido'],['hpHealed','HP curado'],['cardsPicked','Cartas escolhidas'],['cardsSkipped','Ofertas puladas'],['relics','Reliquias'],['potionsUsed','Pocoes usadas'],['deathEncounter','Encontro fatal']];
document.addEventListener('DOMContentLoaded',()=>{bindNavigation();bindUpload();bindSettings();hydrateMetricControls();restoreTheme();loadStoredData();renderAll()});
function bindNavigation(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active');setTimeout(renderAllCanvases,30)}))}
function bindUpload(){document.getElementById('runFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(files.length)setRuns(await parseFiles(files),`${files.length} arquivos processados.`)});document.getElementById('loadDemo').addEventListener('click',()=>setRuns(makeDemoRuns(),'Exemplo carregado com 12 runs sinteticas.'));document.getElementById('clearData').addEventListener('click',()=>{state.runs=[];state.metrics=null;localStorage.removeItem('slaytracker.runs');document.getElementById('uploadStatus').textContent='Dados limpos.';renderAll()});document.getElementById('resetLayout').addEventListener('click',()=>{state.layout={};localStorage.removeItem('slaytracker.layout');renderWidgets()});document.getElementById('detailSelect').addEventListener('change',renderDetail);document.getElementById('addCustomChart').addEventListener('click',addCustomChart)}
function bindSettings(){document.getElementById('themeToggle').addEventListener('change',e=>{document.body.classList.toggle('light',!e.target.checked);localStorage.setItem('slaytracker.theme',e.target.checked?'dark':'light');renderAllCanvases()});document.querySelectorAll('.analysis-toggle').forEach(i=>i.addEventListener('change',()=>{i.checked?state.enabled.add(i.value):state.enabled.delete(i.value);renderAll()}))}
function restoreTheme(){const theme=localStorage.getItem('slaytracker.theme')||'dark';document.body.classList.toggle('light',theme==='light');document.getElementById('themeToggle').checked=theme!=='light'}
function hydrateMetricControls(){['xMetric','yMetric','groupMetric'].forEach(id=>document.getElementById(id).innerHTML=metricOptions.map(([v,l])=>`<option value="${v}">${l}</option>`).join(''));xMetric.value='floor';yMetric.value='win';groupMetric.value='ascension'}
function loadStoredData(){const s=localStorage.getItem('slaytracker.runs');if(!s)return;try{setRuns(JSON.parse(s),'Dataset anterior restaurado.')}catch{localStorage.removeItem('slaytracker.runs')}}
async function parseFiles(files){const out=[];for(const file of files){try{out.push(normalizeRun(JSON.parse(await file.text()),file.name,out.length))}catch(e){console.warn('Falha ao importar '+file.name,e)}}return out.sort((a,b)=>a.startTime-b.startTime)}
function setRuns(runs,msg){state.runs=runs.map((r,i)=>({...r,runIndex:i+1}));state.metrics=buildMetrics(state.runs);localStorage.setItem('slaytracker.runs',JSON.stringify(state.runs));document.getElementById('uploadStatus').textContent=msg;renderAll();document.querySelector('[data-view="dashboard"]').click()}
function normalizeRun(run,fileName='run.json',fallbackIndex=0){const floors=flattenFloors(run.map_point_history),players=Array.isArray(run.players)?run.players:[],last=[...floors].reverse().flatMap(f=>f.playerStats).find(Boolean)||{},cardEvents=collectCardEvents(floors),cardsPicked=cardEvents.filter(e=>e.wasPicked).length,cardsSkipped=cardEvents.length-cardsPicked,deckSize=countCards(floors,players),relics=floors.reduce((s,f)=>s+f.playerStats.flatMap(st=>st.relic_choices||[]).filter(c=>c.was_picked).length,0),potionsUsed=floors.reduce((s,f)=>s+f.playerStats.flatMap(st=>st.potion_used||[]).length,0),eco=floors.reduce((a,f)=>{f.playerStats.forEach(st=>{a.goldGained+=Number(st.gold_gained||0);a.goldSpent+=Number(st.gold_spent||0);a.damageTaken+=Number(st.damage_taken||0);a.hpHealed+=Number(st.hp_healed||0)});return a},{goldGained:0,goldSpent:0,damageTaken:0,hpHealed:0});return{fileName,seed:run.seed||fileName.replace(/\..+$/,''),startTime:Number(run.start_time||fallbackIndex),ascension:Number(run.ascension||0),gameMode:run.game_mode||'unknown',win:Boolean(run.win),wasAbandoned:Boolean(run.was_abandoned),runTimeMinutes:Math.round(Number(run.run_time||0)/60),floor:floors.length,actCount:Array.isArray(run.acts)?run.acts.length:0,deathEncounter:cleanId(run.killed_by_encounter||'NONE'),deathEvent:cleanId(run.killed_by_event||'NONE'),deckSize,cardsPicked,cardsSkipped,relics,potionsUsed,currentHp:Number(last.current_hp||0),maxHp:Number(last.max_hp||0),cardEvents,floors:floors.map(f=>({floor:f.floor,act:f.act,type:f.type,encounter:f.encounter,damageTaken:f.playerStats.reduce((s,st)=>s+Number(st.damage_taken||0),0),currentHp:f.playerStats[0]?.current_hp??null})),...eco}}
function flattenFloors(history=[]){return(history||[]).flatMap((act,ai)=>(act||[]).map((p,pi)=>{const room=(Array.isArray(p.rooms)?p.rooms:[])[0]||{};return{floor:ai*17+pi+1,act:ai+1,type:p.map_point_type||room.room_type||'unknown',encounter:cleanId(room.model_id||room.room_type||p.map_point_type||'unknown'),playerStats:Array.isArray(p.player_stats)?p.player_stats:[]}}))}
function collectCardEvents(floors){const out=[];floors.forEach(f=>f.playerStats.forEach(st=>(st.card_choices||[]).forEach(c=>out.push({id:cleanId(c.card?.id||c.id||'UNKNOWN_CARD'),floor:f.floor,wasPicked:Boolean(c.was_picked)}))));return out}
function countCards(floors,players){const p=players.flatMap(pl=>pl?.deck||pl?.cards||pl?.master_deck||[]).filter(Boolean).length;if(p)return p;const gained=floors.reduce((s,f)=>s+f.playerStats.flatMap(st=>st.cards_gained||[]).length,0);return Math.max(10,10+gained)}
function buildMetrics(runs){const wins=runs.filter(r=>r.win).length,deaths=runs.filter(r=>!r.win&&!r.wasAbandoned);return{runs,summary:{total:runs.length,wins,winRate:pct(wins,runs.length),deaths:deaths.length,avgFloor:avg(runs.map(r=>r.floor)),avgDeck:avg(runs.map(r=>r.deckSize))},deckBuckets:bucketDecks(runs),cardStats:buildCardStats(runs),deathStats:buildDeathStats(deaths),floorProgress:runs.map(r=>({label:'Run '+r.runIndex,value:r.floor,win:r.win})),economy:[{label:'Ouro ganho',value:sum(runs,'goldGained')},{label:'Ouro gasto',value:sum(runs,'goldSpent')},{label:'Dano recebido',value:sum(runs,'damageTaken')},{label:'HP curado',value:sum(runs,'hpHealed')}]}}
function bucketDecks(runs){return[[10,19,'10-19'],[20,29,'20-29'],[30,39,'30-39'],[40,49,'40-49'],[50,1/0,'50+']].map(([min,max,label])=>{const rows=runs.filter(r=>r.deckSize>=min&&r.deckSize<=max);return{label,value:pct(rows.filter(r=>r.win).length,rows.length),count:rows.length}})}
function buildCardStats(runs){const m=new Map();runs.forEach(run=>{const seen=new Set();run.cardEvents.forEach(e=>{const row=m.get(e.id)||{card:e.id,offered:0,picked:0,winsWithPick:0,runsWithPick:0};row.offered++;if(e.wasPicked){row.picked++;seen.add(e.id)}m.set(e.id,row)});seen.forEach(id=>{const row=m.get(id);row.runsWithPick++;row.winsWithPick+=run.win?1:0})});return[...m.values()].map(r=>({...r,pickRate:pct(r.picked,r.offered),winRate:pct(r.winsWithPick,r.runsWithPick)})).sort((a,b)=>b.offered-a.offered||b.pickRate-a.pickRate)}
function buildDeathStats(deaths){return[...groupBy(deaths,r=>r.deathEncounter||'UNKNOWN').entries()].map(([encounter,rows])=>({encounter,deaths:rows.length,avgFloor:avg(rows.map(r=>r.floor)),avgDeck:avg(rows.map(r=>r.deckSize))})).sort((a,b)=>b.deaths-a.deaths)}
function renderAll(){renderKpis();renderWidgets();renderDetailOptions();renderDetail()}
function renderKpis(){const g=document.getElementById('kpiGrid');if(!state.metrics){g.innerHTML='';return}const s=state.metrics.summary;g.innerHTML=[['Runs',s.total],['Win rate',s.winRate+'%'],['Mortes',s.deaths],['Floor medio',s.avgFloor.toFixed(1)],['Deck medio',s.avgDeck.toFixed(1)]].map(([l,v])=>`<div class="kpi"><span class="muted">${l}</span><strong>${v}</strong></div>`).join('')}
function renderWidgets(){const g=document.getElementById('widgetGrid');g.innerHTML='';if(!state.metrics){g.innerHTML='<div class="empty-state widget full">Importe suas runs para montar o dashboard.</div>';return}widgets.filter(w=>state.enabled.has(w.analysis)).forEach(w=>g.appendChild(createWidget(w)));bindDrag(g);renderAllCanvases()}
function createWidget(c){const t=document.getElementById('widgetTemplate').content.cloneNode(true),e=t.querySelector('.widget');e.dataset.widgetId=c.id;e.classList.add(state.layout[c.id]||'medium');e.querySelector('.widget-type').textContent=c.type;e.querySelector('h3').textContent=c.title;c.render(e.querySelector('.widget-body'));e.querySelector('.expand').onclick=()=>resizeWidget(e,1);e.querySelector('.shrink').onclick=()=>resizeWidget(e,-1);return e}
function resizeWidget(e,d){const sizes=['small','medium','large','full'],id=e.dataset.widgetId,cur=sizes.findIndex(s=>e.classList.contains(s)),next=sizes[Math.max(0,Math.min(sizes.length-1,cur+d))]||'medium';e.classList.remove(...sizes);e.classList.add(next);state.layout[id]=next;localStorage.setItem('slaytracker.layout',JSON.stringify(state.layout));renderAllCanvases()}
function bindDrag(g){let dragged=null;g.querySelectorAll('.widget').forEach(w=>{w.ondragstart=()=>{dragged=w;w.classList.add('dragging')};w.ondragend=()=>{dragged?.classList.remove('dragging');dragged=null};w.ondragover=e=>{e.preventDefault();if(!dragged||dragged===w)return;const r=w.getBoundingClientRect();g.insertBefore(dragged,e.clientY>r.top+r.height/2?w.nextSibling:w)}})}
function renderFloorProgress(c){drawCanvas(c,(ctx,b)=>drawLine(ctx,b,state.metrics.floorProgress,'Floor'))}function renderDeckWinRate(c){drawCanvas(c,(ctx,b)=>drawBars(ctx,b,state.metrics.deckBuckets,'Win rate %',true))}function renderEconomy(c){drawCanvas(c,(ctx,b)=>drawBars(ctx,b,state.metrics.economy,'Total',false))}
function renderCardStats(c){c.innerHTML=table(['Carta','Ofertas','Picks','Pick rate','Win rate'],state.metrics.cardStats.slice(0,18).map(r=>[r.card,r.offered,r.picked,r.pickRate+'%',r.winRate+'%']))}function renderDeathStats(c){c.innerHTML=table(['Encontro','Mortes','Floor medio','Deck medio'],state.metrics.deathStats.slice(0,18).map(r=>[r.encounter,r.deaths,r.avgFloor.toFixed(1),r.avgDeck.toFixed(1)]))}function renderRunTable(c){c.innerHTML=table(['Run','Seed','A','Win','Floor','Deck','Tempo','Morte'],state.metrics.runs.map(r=>[r.runIndex,r.seed,r.ascension,r.win?'Sim':'Nao',r.floor,r.deckSize,r.runTimeMinutes+'m',r.deathEncounter]))}
function renderDetailOptions(){document.getElementById('detailSelect').innerHTML=widgets.filter(w=>state.enabled.has(w.analysis)).map(w=>`<option value="${w.id}">${w.title}</option>`).join('')}function renderDetail(){const c=document.getElementById('detailContent');if(!state.metrics){c.innerHTML='<div class="empty-state">Importe runs para visualizar tabelas e graficos.</div>';return}const w=widgets.find(x=>x.id===document.getElementById('detailSelect').value)||widgets[0];c.innerHTML='';w.render(c);renderAllCanvases()}
function addCustomChart(){if(!state.metrics)return;const x=xMetric.value,y=yMetric.value,g=groupMetric.value,type=chartType.value,label=`${labelFor(x)} x ${labelFor(y)} por ${labelFor(g)}`,card=document.createElement('article');card.className='custom-card';card.innerHTML=`<h3>${label}</h3><div class="widget-body"></div>`;customCharts.prepend(card);const rows=customRows(x,y,g);drawCanvas(card.querySelector('.widget-body'),(ctx,b)=>type==='scatter'?drawScatter(ctx,b,rows,x,y):type==='line'?drawLine(ctx,b,rows.map(r=>({label:r.label,value:r.value})),labelFor(y)):drawBars(ctx,b,rows,labelFor(y),false))}
function customRows(x,y,g){return[...groupBy(state.metrics.runs,r=>String(r[g]??'N/A')).entries()].map(([label,runs])=>({label,x:avg(runs.map(r=>Number(r[x])||0)),value:y==='win'?pct(runs.filter(r=>r.win).length,runs.length):avg(runs.map(r=>Number(r[y])||0))}))}
function drawCanvas(c,draw){c.innerHTML='<canvas></canvas>';const canvas=c.querySelector('canvas');canvas._draw=draw;renderCanvas(canvas)}function renderAllCanvases(){document.querySelectorAll('canvas').forEach(renderCanvas)}function renderCanvas(canvas){if(!canvas._draw)return;const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(320,r.width*d);canvas.height=Math.max(240,r.height*d);const ctx=canvas.getContext('2d');ctx.scale(d,d);canvas._draw(ctx,{width:canvas.width/d,height:canvas.height/d})}
function drawBars(ctx,b,data,label,percent){clearChart(ctx,b);const p=46,max=Math.max(1,...data.map(i=>i.value)),w=(b.width-p*2)/Math.max(1,data.length);data.forEach((it,i)=>{const h=(b.height-p*2)*it.value/max,x=p+i*w+w*.14,y=b.height-p-h;ctx.fillStyle=i%2?css('--accent-2'):css('--accent');ctx.fillRect(x,y,w*.7,h);ctx.fillStyle=css('--text');ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(it.label,x+w*.35,b.height-18);ctx.fillText(`${it.value.toFixed(percent?0:1)}${percent?'%':''}`,x+w*.35,y-7)});axis(ctx,b,label)}
function drawLine(ctx,b,data,label){clearChart(ctx,b);const p=46,max=Math.max(1,...data.map(i=>i.value)),step=(b.width-p*2)/Math.max(1,data.length-1);ctx.strokeStyle=css('--accent-2');ctx.lineWidth=3;ctx.beginPath();data.forEach((it,i)=>{const x=p+i*step,y=b.height-p-(b.height-p*2)*it.value/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();data.forEach((it,i)=>{const x=p+i*step,y=b.height-p-(b.height-p*2)*it.value/max;ctx.fillStyle=it.win?css('--good'):css('--accent');ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()});axis(ctx,b,label)}
function drawScatter(ctx,b,rows,xl,yl){clearChart(ctx,b);const p=46,mx=Math.max(1,...rows.map(r=>r.x)),my=Math.max(1,...rows.map(r=>r.value));rows.forEach((r,i)=>{ctx.fillStyle=i%2?css('--accent'):css('--accent-2');ctx.beginPath();ctx.arc(p+(b.width-p*2)*r.x/mx,b.height-p-(b.height-p*2)*r.value/my,7,0,Math.PI*2);ctx.fill()});axis(ctx,b,`${labelFor(xl)} / ${labelFor(yl)}`)}
function clearChart(ctx,b){ctx.clearRect(0,0,b.width,b.height);ctx.fillStyle=css('--panel');ctx.fillRect(0,0,b.width,b.height);ctx.strokeStyle=css('--line');for(let i=0;i<4;i++){const y=46+i*((b.height-92)/3);ctx.beginPath();ctx.moveTo(46,y);ctx.lineTo(b.width-46,y);ctx.stroke()}}function axis(ctx,b,label){ctx.fillStyle=css('--muted');ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText(label,12,22);ctx.strokeStyle=css('--line');ctx.beginPath();ctx.moveTo(46,b.height-46);ctx.lineTo(b.width-46,b.height-46);ctx.stroke()}
function table(h,rows){return`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${escapeHtml(String(c??''))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}function cleanId(v){return String(v||'NONE').replace(/^(CARD|RELIC|POTION|ENCOUNTER|EVENT|MONSTER|ACT|NONE)\./,'').replaceAll('_',' ')}function avg(v){const n=v.map(Number).filter(Number.isFinite);return n.length?n.reduce((a,b)=>a+b,0)/n.length:0}function sum(rows,key){return rows.reduce((t,r)=>t+Number(r[key]||0),0)}function pct(part,total){return total?Math.round(part/total*1000)/10:0}function groupBy(rows,get){return rows.reduce((m,r)=>{const k=get(r);m.set(k,[...(m.get(k)||[]),r]);return m},new Map())}function labelFor(v){return metricOptions.find(([k])=>k===v)?.[1]||v}function css(v){return getComputedStyle(document.body).getPropertyValue(v).trim()}function escapeHtml(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function makeDemoRuns(){return Array.from({length:12},(_,i)=>{const floor=12+i*3+(i%3)*4,win=i%5===0,cards=['STRIKE','SHROUD','NEGATIVE PULSE','WISP','SCOURGE','MAD SCIENCE'];return{fileName:`demo-${i+1}.run`,seed:`DEMO${i+1}`,startTime:i,runIndex:i+1,ascension:i%10,gameMode:'standard',win,wasAbandoned:false,runTimeMinutes:24+i*3,floor,actCount:Math.ceil(floor/17),deathEncounter:win?'NONE':['SCROLLS OF BITING','CULTIST','CONSTRUCT MENAGERIE'][i%3],deathEvent:'NONE',deckSize:18+i*2,cardsPicked:8+i,cardsSkipped:12+i,relics:2+i%7,potionsUsed:i%4,currentHp:win?41:0,maxHp:70+i,goldGained:110+i*24,goldSpent:30+i*11,damageTaken:20+i*9,hpHealed:15+i*5,cardEvents:cards.flatMap((id,j)=>[{id,floor:j+1,wasPicked:(j+i)%3===0},{id,floor:j+3,wasPicked:(j+i)%4===0}]),floors:[]}})}
window.addEventListener('resize',renderAllCanvases);
